apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-monitor
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    targetRevision: main
    path: kubernetes/cloud/yamls/monitoring
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
