apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-sync
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    targetRevision: main
    path: kubernetes/cloud/yamls/time_sync
  destination:
    server: "https://kubernetes.default.svc"
    namespace: time-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true