version: "3.8"

services:
  spark-history-server:
    build: .
    container_name: spark-history-server
    ports:
      - "18080:18080"
    env_file:
      - .env
    volumes:
      - ./spark-events:/opt/spark/logs/events
    restart: unless-stopped
