apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: minio-community
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    path: infrastructure/helm-charts/minio-community
    targetRevision: main
    helm:
      valueFiles:
        - values-standalone.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: deepstorage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
