apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: spark-operator
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    path: kubernetes/edge/helm-charts/spark-operator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-pod-monitor
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    targetRevision: main
    path: kubernetes/edge/yamls/monitoring
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-jobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true