apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: spark-history-server
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "git@bitbucket.org:certi_repos/datalake-labfaber.git"
    path: infrastructure/helm-charts/spark-history-server
    targetRevision: development
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-jobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
