apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: airbyte-default
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://airbytehq.github.io/helm-charts"
    chart: airbyte
    targetRevision: 1.2.0
    helm:
      values: |
        global:
          airbyteUrl: "airbyte-cpc.certi.org.br"
        webapp:
          ingress:
            # -- Set to true to enable ingress record generation
            enabled: true
            # -- Specifies ingressClassName for clusters >= 1.18+
            className: "traefik"
            # -- Ingress annotations done as key:value pairs
            annotations:
              ingress.kubernetes.io/ssl-redirect: "false"
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
            # -- The list of hostnames to be covered with this ingress record.
            hosts:
              - host: airbyte-cpc.certi.org.br
                paths:
                  - path: /
                    pathType: Prefix
            # -- Custom ingress TLS configuration
            tls:
              - secretName: streaming-tls-scret
                hosts:
                - airbyte-cpc.certi.org.br
        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airbyte
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
