apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: kafka-operator
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/ArthurKretzer/streaming-pipeline.git"
    path: infrastructure/helm-charts/kafka-operator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-broker
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: infrastructure/yamls/ingestion/broker
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-connect
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: infrastructure/yamls/ingestion/kafka-connect
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-rebalance
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: infrastructure/yamls/ingestion/cruise-control
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-metrics
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: infrastructure/yamls/ingestion/metrics
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-schema-registry
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: infrastructure/helm-charts/cp-schema-registry
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-kafka-ui
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ArthurKretzer/streaming-pipeline.git'
    targetRevision: main
    path: kubernetes/edge/helm-charts/kafka-ui
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
