apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: streaming-kafka-rebalance
  labels:
    strimzi.io/cluster: streaming
spec:
  goals:
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal
    - TopicReplicaDistributionGoal
    - MinTopicLeadersPerBrokerGoal
    - LeaderReplicaDistributionGoal
    - DiskUsageDistributionGoal
    - IntraBrokerDiskCapacityGoal
    - IntraBrokerDiskUsageDistributionGoal
